version: 2
before:
  hooks:
    - go mod tidy
builds:
  - binary: sitectl-wp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }}
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^.github"
brews:
  - name: sitectl-wp
    homepage: "https://github.com/libops/sitectl-wp"
    commit_author:
      name: sitectl-dev[bot]
      email: 2408410+sitectl-dev[bot]@users.noreply.github.com
    repository:
      owner: libops
      name: homebrew
    dependencies:
      - name: "libops/homebrew/sitectl"
      - name: "libops/homebrew/sitectl-mariadb"
      - name: "libops/homebrew/sitectl-postgres"
      - name: "libops/homebrew/sitectl-solr"
      - name: "libops/homebrew/sitectl-traefik"
      - name: "libops/homebrew/sitectl-triplet"
nfpms:
  - id: sitectl-wp
    package_name: sitectl-wp
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: libops
    homepage: "https://github.com/libops/sitectl-wp"
    description: "A sitectl plugin for WordPress stacks"
    maintainer: "Joe Corall <joe@libops.io>"
    license: "MIT"
    formats:
      - apk
      - deb
      - rpm
    mtime: "{{ .CommitDate }}"
    builds:
      - sitectl-wp
    dependencies:
      - sitectl
      - sitectl-mariadb
      - sitectl-postgres
      - sitectl-solr
      - sitectl-traefik
      - sitectl-triplet
