name: integration-test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: integration-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  create-wp:
    name: sitectl create wp ${{ matrix.create_definition }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - create_definition: default
            create_args: ""
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version: "1.26.x"

      - name: Install sitectl
        uses: libops/.github/.github/actions/install-sitectl@90a9272d0829c878a682ba636bc155c2b06c7939 # main
        with:
          packages: sitectl
          package-versions: sitectl=0.40.0
          allow-unversioned: false

      - name: setup git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Run create integration test
        run: make integration-test CREATE_DEFINITION=${{ matrix.create_definition }} CREATE_ARGS="${{ matrix.create_args }}"
        env:
          TERM: xterm-256color
